#include "TableGlobals.h"

StatoSistema statoAttuale = VIEW;
TFT_eSPI tft = TFT_eSPI();
Adafruit_NeoPixel strip(NUM_LEDS, LED_PIN, NEO_GRB + NEO_KHZ800);
Adafruit_PN532 nfc(SDA_NFC, SCL_NFC);


Reservation reservations[MAX_RESERVATIONS];
int reservationsCount = 0;
int64_t nextLocalId = -1;
String reassembled;
uint32_t currentMsgId = 0;
uint16_t currentTableId = 0;
uint16_t expectedChunks = 0;
uint16_t receivedChunks = 0;
bool started = false;
bool timeSynced = false;
uint32_t lastClockPrintMs = 0;
String pendingReservationsJson;
bool pendingReservationsReady = false;
portMUX_TYPE pendingReservationsMux = portMUX_INITIALIZER_UNLOCKED;
uint8_t knownHubMac[6] = {0};
bool hubMacKnown = false;
bool bookingPending = false;
uint8_t bookingPendingAction = BOOK_ACTION_NONE;
uint32_t bookingPendingMsgId = 0;
uint32_t bookingPendingStartMs = 0;
uint32_t bookingPendingOraInizio = 0;
uint32_t bookingPendingOraFine = 0;
uint64_t bookingPendingReservationId = 0;
String bookingPendingUid;
bool bookingPendingFromTable = false;
uint32_t nextBookingMsgId = 1;
bool bookingErrorVisible = false;
unsigned long bookingErrorUntilMs = 0;
bool bookingErrorReturnToBooking = false;
String currentBookingUidHex;
bool bookingResultReady = false;
BookingResPacket bookingResult;
portMUX_TYPE bookingResultMux = portMUX_INITIALIZER_UNLOCKED;
bool presenzaConfermata = false;
bool inAttesaConferma = false;
bool ultimoStatoOn = false;
unsigned long ultimoOn = 0;
unsigned long primaPresenza = 0;
String rigaRadar;
int bookingEndMinutes = 10 * 60; // minuti da mezzanotte, step 15
bool bloccoLeds = false;
unsigned long startAssenza = 0;
unsigned long checkInPresenceStartMs = 0;
int64_t checkInTrackingReservationId = 0;
unsigned long startPresenza = 0;
unsigned long lastDisplayRefreshMs = 0;
bool presenceInviteVisible = false;
TouchButtonState btnOut1 = {TOUCH_OUT1_PIN, false, false, false, 0};
TouchButtonState btnOut2 = {TOUCH_OUT2_PIN, false, false, false, 0};
TouchButtonState btnOut3 = {TOUCH_OUT3_PIN, false, false, false, 0};
TouchButtonState btnOut4 = {TOUCH_OUT4_PIN, false, false, false, 0};
unsigned long bookingConfirmHoldStartMs = 0;
unsigned long bookingMinusHoldStartMs = 0;
unsigned long bookingMinusLastRepeatMs = 0;
unsigned long bookingPlusHoldStartMs = 0;
unsigned long bookingPlusLastRepeatMs = 0;
